In [1]:
import warnings 
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd 
import numpy as np 

In [3]:
df=pd.read_csv('Data_for_UCI_named.csv')
df=df.drop(['stab'],axis=1)
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

##### Q Which method can we use to best fit a data in Logistic Regression?
###### A Maximum likelihood


#### -------------------------------------------------------------------------------------------------

##### Q Why do we use weak learners in boosting?
######  A To prevent overfitting

### -------------------------------------------------------------------------

##### Q You are building a classifier and the accuracy is poor on both the training and test sets. Which would you use to try to improve the performance?
###### A Boosting

### --------------------------------------------------------------------------------------


##### Q What is the entropy of the target variable if its actual values are given as:

[1,0,1,1,0,1,0]
###### A - 3/7 log(3/7) - 4/7 log(4/7)

In [4]:
X_data=df.drop('stabf', axis=1)
Y_data=df[['stabf']]

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(X_data, Y_data, test_size=0.2, random_state=1)

In [6]:
from sklearn.preprocessing import StandardScaler
myscaler=StandardScaler()
Xt_Scaled=pd.DataFrame(myscaler.fit_transform(x_train), columns=x_train.columns)
Xtest_Scaled=pd.DataFrame(myscaler.transform(x_test), columns=x_test.columns)

print(Xt_Scaled.head());
print(Xtest_Scaled.head());

       tau1      tau2      tau3      tau4        p1        p2        p3  \
0  0.367327 -0.986042  0.650447  1.547527 -0.291490  0.061535  1.293862   
1 -0.064659  0.089437  1.035079 -1.641494  0.619865 -0.067235 -1.502925   
2 -1.467850  1.298418 -0.502536  1.166046 -0.180521  0.490603  0.682560   
3  0.820081  0.529920  1.299657 -1.141975 -0.812854 -0.763632  1.521579   
4  0.665424 -1.425627  0.312300  0.919137 -1.614296  0.760315  1.422019   

         p4        g1        g2        g3        g4  
0 -0.845074  0.160918  0.339859  0.585568  0.492239  
1  0.486613 -0.293143 -1.558488  1.429649 -1.443521  
2 -0.855302  1.399350  1.451534 -1.045743  0.492489  
3  0.658780 -0.958319  1.361958  1.604140  0.275303  
4  0.639243  1.676895  0.695660  1.137504 -1.312575  
       tau1      tau2      tau3      tau4        p1        p2        p3  \
0  0.593951 -0.412733  1.503924  1.116943  0.403423 -1.492971 -0.785033   
1  0.202190  0.374416 -0.188800 -0.522268 -0.225967 -1.058483  0.420047   


In [7]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_train =pd.DataFrame(encoder.fit_transform(y_train.reset_index(drop=True)), columns=y_train.columns)
y_test = pd.DataFrame(encoder.transform(y_test.reset_index(drop=True)),columns=y_test.columns)

In [8]:
def score_data(y_test,pred_y, clf):
  print('\n\n'+clf)
  print("\n CONFUSION MATRIX \n", confusion_matrix(y_test,pred_y))
  print(classification_report(y_test,pred_y))
  print("Accuracy Score is: ", accuracy_score(y_test, pred_y))

In [9]:
from sklearn.ensemble import RandomForestClassifier
Rf=RandomForestClassifier(n_estimators=100, random_state=1)
Rf.fit(Xt_Scaled,y_train)
pred_y=pd.Series(Rf.predict(Xtest_Scaled))
pred_y.value_counts()

1    1320
0     680
dtype: int64

In [10]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
score_data(y_test, pred_y,'RandomForest Classifier')



RandomForest Classifier

 CONFUSION MATRIX 
 [[ 625   87]
 [  55 1233]]
              precision    recall  f1-score   support

           0       0.92      0.88      0.90       712
           1       0.93      0.96      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000

Accuracy Score is:  0.929


In [11]:
from xgboost import XGBClassifier
clf=XGBClassifier()
clf.fit(Xt_Scaled,y_train)
pred_y=clf.predict(Xtest_Scaled)
score_data(y_test, pred_y,'XGBClassifier')

[21:39:59] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier

 CONFUSION MATRIX 
 [[ 648   64]
 [  45 1243]]
              precision    recall  f1-score   support

           0       0.94      0.91      0.92       712
           1       0.95      0.97      0.96      1288

    accuracy                           0.95      2000
   macro avg       0.94      0.94      0.94      2000
weighted avg       0.95      0.95      0.95      2000

Accuracy Score is:  0.9455


In [12]:
from lightgbm import LGBMClassifier
clf= LGBMClassifier()
clf.fit(Xt_Scaled,y_train)
pred_y=clf.predict(Xtest_Scaled)
score_data(y_test, pred_y,'LGBM')



LGBM

 CONFUSION MATRIX 
 [[ 641   71]
 [  50 1238]]
              precision    recall  f1-score   support

           0       0.93      0.90      0.91       712
           1       0.95      0.96      0.95      1288

    accuracy                           0.94      2000
   macro avg       0.94      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000

Accuracy Score is:  0.9395


In [13]:
from sklearn.ensemble import ExtraTreesClassifier
ext_clf=ExtraTreesClassifier()
ext_clf.fit(Xt_Scaled,y_train)
pred_y=ext_clf.predict(Xtest_Scaled)
score_data(y_test, pred_y, 'ExtraTreesClassifier Initially')



ExtraTreesClassifier Initially

 CONFUSION MATRIX 
 [[ 599  113]
 [  33 1255]]
              precision    recall  f1-score   support

           0       0.95      0.84      0.89       712
           1       0.92      0.97      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000

Accuracy Score is:  0.927


In [14]:
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None] 
hyperparameter_grid = {'n_estimators': n_estimators,'min_samples_leaf': min_samples_leaf,'min_samples_split': min_samples_split,'max_features': max_features}
from sklearn.model_selection import RandomizedSearchCV
etc_clf=ExtraTreesClassifier()
rdm = RandomizedSearchCV(etc_clf, param_distributions = hyperparameter_grid, cv=5, n_iter=10, n_jobs=-1, verbose=1, random_state=1, scoring='accuracy')
rdm.fit(Xt_Scaled, y_train)
rdm.best_params_

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:    5.2s
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:   13.4s finished


{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 8,
 'max_features': None}

In [15]:
etc_clf_opt=ExtraTreesClassifier(max_features=None,min_samples_leaf=8,min_samples_split=2, n_estimators=1000)
etc_clf_opt.fit(Xt_Scaled, y_train)
pred_y=etc_clf_opt.predict(Xtest_Scaled)
score_data(y_test, pred_y, clf='ExtraTreesClassifier Optimal')




ExtraTreesClassifier Optimal

 CONFUSION MATRIX 
 [[ 619   93]
 [  51 1237]]
              precision    recall  f1-score   support

           0       0.92      0.87      0.90       712
           1       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000

Accuracy Score is:  0.928


In [16]:
feature_imp=etc_clf_opt.feature_importances_

xyz=pd.DataFrame(feature_imp, index=Xt_Scaled.columns, columns=['Importance'])
print("Max Importance is of: ", xyz[['Importance']].idxmax())
print("Min Importance is of: ", xyz[['Importance']].idxmin())

Max Importance is of:  Importance    tau2
dtype: object
Min Importance is of:  Importance    p1
dtype: object


 ### Thank You!!!
 ###### Marks-80/100